# Generated by Django 2.1.5 on 2019-05-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatingTs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_and_Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(verbose_name='lesson_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
            ],
        ),
    ]
